# Generated by Django 2.2.24 on 2021-09-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailKontrakBahan',
            fields=[
                ('kode', models.IntegerField(db_column='kode', primary_key=True, serialize=False)),
                ('KategoriBahan', models.CharField(blank=True, db_column='KategoriBahan', max_length=10, null=True)),
                ('Qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
            ],
            options={
                'db_table': 'DetailKontrakBahan',
                'managed': False,
            },
        ),
    ]
