# Generated by Django 2.2.24 on 2021-10-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_detailkontrakperlengkapan'),
    ]

    operations = [
        migrations.CreateModel(
            name='STSPR',
            fields=[
                ('Kode', models.CharField(db_column='Kode', max_length=10, primary_key=True, serialize=False)),
                ('JobOrder', models.CharField(blank=True, db_column='JobOrder', max_length=10, null=True)),
                ('KetJasTre', models.TextField(blank=True, db_column='KetJasTre', null=True)),
                ('NoInvoice', models.CharField(blank=True, db_column='NoInvoice', max_length=50, null=True)),
                ('NoRekening', models.CharField(blank=True, db_column='NoRekening', max_length=200, null=True)),
                ('Tanggal', models.DateTimeField(blank=True, db_column='Tanggal', null=True)),
                ('WaktuMulai', models.DateTimeField(blank=True, db_column='WaktuMulai', null=True)),
                ('WaktuSelesai', models.DateTimeField(blank=True, db_column='WaktuSelesai', null=True)),
                ('Teknisi', models.CharField(blank=True, db_column='Teknisi', max_length=10, null=True)),
                ('JenisPekerjaan', models.CharField(blank=True, db_column='JenisPekerjaan', max_length=200, null=True)),
                ('Jumlah', models.IntegerField(blank=True, db_column='Jumlah', null=True)),
                ('GrandTotal', models.DecimalField(blank=True, db_column='GrandTotal', decimal_places=4, max_digits=12, null=True)),
                ('Harga', models.DecimalField(blank=True, db_column='Harga', decimal_places=4, max_digits=12, null=True)),
                ('PPN1', models.DecimalField(blank=True, db_column='PPN1', decimal_places=4, max_digits=12, null=True)),
                ('Tindakan', models.TextField(blank=True, db_column='Tindakan', null=True)),
                ('CreateBy', models.CharField(blank=True, db_column='CreateBy', max_length=10, null=True)),
                ('CreateDate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('Operator', models.CharField(blank=True, db_column='Operator', max_length=10, null=True)),
                ('TglEntry', models.DateTimeField(blank=True, db_column='TglEntry', null=True)),
                ('PPN', models.BooleanField(blank=True, db_column='PPN', default=True, null=True)),
                ('TidakInvoice', models.BooleanField(blank=True, db_column='TidakInvoice', default=True, null=True)),
                ('NoFakturPajak', models.CharField(blank=True, db_column='NoFakturPajak', max_length=50, null=True)),
                ('Grup', models.CharField(blank=True, db_column='Grup', max_length=10, null=True)),
                ('TglTerimaInvoice', models.DateTimeField(blank=True, db_column='TglTerimaInvoice', null=True)),
                ('Tanggal2', models.DateTimeField(blank=True, db_column='Tanggal2', null=True)),
                ('STS', models.CharField(blank=True, db_column='STS', max_length=10, null=True)),
                ('Memo', models.TextField(blank=True, db_column='Memo', null=True)),
                ('TglSelesaiLaporan', models.DateTimeField(blank=True, db_column='TglSelesaiLaporan', null=True)),
                ('Status1', models.CharField(blank=True, db_column='Status1', max_length=20, null=True)),
                ('Alasan', models.TextField(blank=True, db_column='Alasan', null=True)),
                ('NoOrder', models.CharField(blank=True, db_column='NoOrder', max_length=50, null=True)),
            ],
            options={
                'db_table': 'STSPR',
                'managed': False,
            },
        ),
    ]
