# Generated by Django 2.2.24 on 2021-10-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_stspr'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailSTSPR',
            fields=[
                ('Kode', models.IntegerField(db_column='Kode', primary_key=True, serialize=False)),
                ('Qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('PlafonQty', models.IntegerField(blank=True, db_column='PlafonQty', null=True)),
                ('Invoice', models.CharField(blank=True, db_column='Invoice', max_length=10, null=True)),
            ],
            options={
                'db_table': 'DetailSTSPR',
                'managed': False,
            },
        ),
    ]
