# Generated by Django 2.2.24 on 2021-10-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_detailstspr'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailSTSPRHarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STSPRH', models.CharField(blank=True, db_column='STSPRH', max_length=10, null=True)),
                ('Tanggal', models.DateTimeField(blank=True, db_column='Tanggal', null=True)),
                ('Komplain', models.BooleanField(blank=True, db_column='Komplain', default=True, null=True)),
                ('Keterangan', models.TextField(blank=True, db_column='Keterangan', null=True)),
                ('JamMulai', models.DateTimeField(blank=True, db_column='JamMulai', null=True)),
                ('JamSelesai', models.DateTimeField(blank=True, db_column='JamSelesai', null=True)),
                ('JenisPekerjaan', models.CharField(blank=True, db_column='JenisPekerjaan', max_length=50, null=True)),
                ('Inspeksi', models.CharField(blank=True, db_column='Inspeksi', max_length=250, null=True)),
                ('Spraying', models.CharField(blank=True, db_column='Spraying', max_length=250, null=True)),
                ('CoolFogging', models.CharField(blank=True, db_column='CoolFogging', max_length=250, null=True)),
                ('ThermalFogging', models.CharField(blank=True, db_column='ThermalFogging', max_length=250, null=True)),
                ('Inspeksi1', models.BooleanField(blank=True, db_column='Inspeksi1', default=True, null=True)),
                ('Spraying1', models.BooleanField(blank=True, db_column='Spraying1', default=True, null=True)),
                ('CoolFogging1', models.BooleanField(blank=True, db_column='CoolFogging1', default=True, null=True)),
                ('ThermalFogging1', models.BooleanField(blank=True, db_column='ThermalFogging1', default=True, null=True)),
                ('PICClient', models.CharField(blank=True, db_column='PICClient', max_length=250, null=True)),
                ('PICClient1', models.BooleanField(blank=True, db_column='PICClient1', default=True, null=True)),
            ],
            options={
                'db_table': 'DetailSTSPRHarian',
                'managed': False,
            },
        ),
    ]
