# Generated by Django 2.2.24 on 2021-10-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_detailstsprharianbahan_detailstsprharianteknisi_detailstsprpin_detailstsprpout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('Kode', models.CharField(db_column='Kode', max_length=10, primary_key=True, serialize=False)),
                ('Nama', models.CharField(blank=True, db_column='Nama', max_length=250, null=True)),
                ('NIK', models.CharField(blank=True, db_column='NIK', max_length=50, null=True)),
                ('NoKTP', models.CharField(blank=True, db_column='NoKTP', max_length=50, null=True)),
                ('NoSIM', models.CharField(blank=True, db_column='NoSIM', max_length=50, null=True)),
                ('Alamat', models.CharField(blank=True, db_column='Alamat', max_length=250, null=True)),
                ('TglLahir', models.DateTimeField(blank=True, db_column='Tanggal', null=True)),
                ('StatusPerkawinan', models.CharField(blank=True, db_column='StatusPerkawinan', max_length=20, null=True)),
                ('Telp', models.CharField(blank=True, db_column='Telp', max_length=20, null=True)),
                ('Hp1', models.CharField(blank=True, db_column='Hp1', max_length=15, null=True)),
                ('Hp2', models.CharField(blank=True, db_column='Hp2', max_length=15, null=True)),
                ('TglBergabung', models.DateTimeField(blank=True, db_column='TglBergabung', null=True)),
                ('TglKeluar', models.DateTimeField(blank=True, db_column='TglKeluar', null=True)),
                ('Keterangan', models.CharField(blank=True, db_column='Keterangan', max_length=50, null=True)),
                ('Bagian', models.CharField(blank=True, db_column='Bagian', max_length=50, null=True)),
                ('Jabatan', models.CharField(blank=True, db_column='Jabatan', max_length=50, null=True)),
                ('Pendidikan', models.CharField(blank=True, db_column='Pendidikan', max_length=50, null=True)),
                ('NoRekening', models.CharField(blank=True, db_column='NoRekening', max_length=50, null=True)),
                ('Bank', models.CharField(blank=True, db_column='Bank', max_length=100, null=True)),
                ('PlafonService', models.DecimalField(blank=True, db_column='PlafonService', decimal_places=4, max_digits=12, null=True)),
                ('Gaji', models.DecimalField(blank=True, db_column='Gaji', decimal_places=4, max_digits=12, null=True)),
                ('TunjanganJabatan', models.DecimalField(blank=True, db_column='TunjanganJabatan', decimal_places=4, max_digits=12, null=True)),
                ('UangMuka', models.DecimalField(blank=True, db_column='UangMuka', decimal_places=4, max_digits=12, null=True)),
                ('Transport', models.DecimalField(blank=True, db_column='Transport', decimal_places=4, max_digits=12, null=True)),
                ('Pulsa', models.DecimalField(blank=True, db_column='Pulsa', decimal_places=4, max_digits=12, null=True)),
                ('Aktif', models.BooleanField(blank=True, db_column='Aktif', default=True, null=True)),
                ('BPJS', models.DecimalField(blank=True, db_column='BPJS', decimal_places=4, max_digits=12, null=True)),
                ('BPJSKetenagaKerjaan', models.DecimalField(blank=True, db_column='BPJSKetenagaKerjaan', decimal_places=4, max_digits=12, null=True)),
                ('NPWP', models.CharField(blank=True, db_column='NPWP', max_length=50, null=True)),
                ('JumlahAnak', models.IntegerField(blank=True, db_column='JumlahAnak', null=True)),
                ('NoKK', models.CharField(blank=True, db_column='NoKK', max_length=50, null=True)),
                ('NamaIstri', models.CharField(blank=True, db_column='NamaIstri', max_length=50, null=True)),
                ('SkillAllowance', models.DecimalField(blank=True, db_column='SkillAllowance', decimal_places=4, max_digits=12, null=True)),
                ('FumigatorAllowance', models.DecimalField(blank=True, db_column='FumigatorAllowance', decimal_places=4, max_digits=12, null=True)),
                ('PositionAllowance', models.DecimalField(blank=True, db_column='PositionAllowance', decimal_places=4, max_digits=12, null=True)),
                ('VehicleRentAllowance', models.DecimalField(blank=True, db_column='VehicleRentAllowance', decimal_places=4, max_digits=12, null=True)),
                ('CreateDate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('CreateBy', models.CharField(blank=True, db_column='CreateBy', max_length=10, null=True)),
                ('Operator', models.CharField(blank=True, db_column='Operator', max_length=10, null=True)),
                ('TglEntry', models.DateTimeField(blank=True, db_column='TglEntry', null=True)),
                ('Departemen', models.CharField(blank=True, db_column='Departemen', max_length=250, null=True)),
                ('StatusPajak', models.CharField(blank=True, db_column='StatusPajak', max_length=50, null=True)),
                ('IuranJKK', models.DecimalField(blank=True, db_column='IuranJKK', decimal_places=4, max_digits=12, null=True)),
                ('IuranJKM', models.DecimalField(blank=True, db_column='IuranJKM', decimal_places=4, max_digits=12, null=True)),
                ('IuranJHT', models.DecimalField(blank=True, db_column='IuranJHT', decimal_places=4, max_digits=12, null=True)),
                ('IuranJHT2', models.DecimalField(blank=True, db_column='IuranJHT2', decimal_places=4, max_digits=12, null=True)),
                ('IuranJP', models.DecimalField(blank=True, db_column='IuranJP', decimal_places=4, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'Pegawai',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='detailstsprpin',
            table='DetailSTSPRPIn',
        ),
        migrations.AlterModelTable(
            name='detailstsprpout',
            table='DetailSTSPRPOut',
        ),
    ]
