# Generated by Django 2.2.24 on 2021-11-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211022_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bahan',
            options={'managed': False, 'verbose_name_plural': 'Bahan'},
        ),
        migrations.AlterModelOptions(
            name='kontrak',
            options={'managed': False, 'verbose_name_plural': 'Kontrak'},
        ),
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'managed': False, 'verbose_name_plural': 'Pelanggan'},
        ),
        migrations.AlterModelOptions(
            name='penawaran',
            options={'managed': False, 'verbose_name_plural': 'Penawaran'},
        ),
        migrations.AlterModelOptions(
            name='stspr',
            options={'managed': False, 'verbose_name_plural': 'STSPR'},
        ),
    ]
